CREATE TABLE AppInfo(
    xmh_id bigint generated by default as identity
)@@$$%%;

CREATE TABLE ledger(
    xmh_id bigint generated by default as identity,
    name varchar(50) unique,
    level smallint,
    c1Part1Len smallint,
    c1Part2Len smallint,
    c2Len smallint,
    c3Len smallint,
    c4Len smallint,
    c5Len smallint,
    c6Len smallint,
    c7Len smallint,
    c8Len smallint,
    c9Len smallint,
    isTemplate smallint,
    acId bigint not null
)@@$$%%;

CREATE TABLE currency(
    xmh_id bigint generated by default as identity,
    name varchar(10) unique,
    code varchar(3) unique
)@@$$%%;

CREATE TABLE LedgerCurrencies(
    ledgerId bigint,
    currencyId bigint
)@@$$%%;

CREATE TABLE accountclassification(
    xmh_id bigint generated by default as identity,
    name varchar(30),
    code varchar(100),
    parentId bigint
)@@$$%%;

CREATE TABLE xmhuser(
    xmh_id bigint generated by default as identity,
    name varchar(30),
    password varchar(100)
)@@$$%%;

CREATE TABLE ledgerusers(
    ledgerid bigint,
    userid bigint
)@@$$%%;

CREATE TABLE xmhrole(
    ledgerId bigint,
    userId bigint
)@@$$%%;

CREATE TABLE xmhgroup(
    xmh_id bigint generated by default as identity,
    name varchar(30) not null,
    isAdmin smallint,
    parentId bigint
)@@$$%%;

CREATE TABLE groupUsers(
    groupId bigint,
    userId bigint
)@@$$%%;

CREATE TABLE ledgerGroups(
    ledgerId bigint,
    groupId bigint
)@@$$%%;

